# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 818)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layerSlider = QtWidgets.QSlider(self.centralwidget)
        self.layerSlider.setOrientation(QtCore.Qt.Vertical)
        self.layerSlider.setObjectName("layerSlider")
        self.horizontalLayout.addWidget(self.layerSlider)
        self.graphicsView = QtImageViewer(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.zRetractSpeedEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.zRetractSpeedEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.zRetractSpeedEdit.setObjectName("zRetractSpeedEdit")
        self.gridLayout.addWidget(self.zRetractSpeedEdit, 8, 1, 1, 1)
        self.previewWEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.previewWEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.previewWEdit.setObjectName("previewWEdit")
        self.gridLayout.addWidget(self.previewWEdit, 11, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 11, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.bottomLayersEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.bottomLayersEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.bottomLayersEdit.setObjectName("bottomLayersEdit")
        self.gridLayout.addWidget(self.bottomLayersEdit, 5, 1, 1, 1)
        self.xyPixelSizeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.xyPixelSizeEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.xyPixelSizeEdit.setObjectName("xyPixelSizeEdit")
        self.gridLayout.addWidget(self.xyPixelSizeEdit, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.totalVolumeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalVolumeEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.totalVolumeEdit.setObjectName("totalVolumeEdit")
        self.gridLayout.addWidget(self.totalVolumeEdit, 9, 1, 1, 1)
        self.normalExposureEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.normalExposureEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.normalExposureEdit.setObjectName("normalExposureEdit")
        self.gridLayout.addWidget(self.normalExposureEdit, 2, 1, 1, 1)
        self.bottomExposureEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.bottomExposureEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.bottomExposureEdit.setObjectName("bottomExposureEdit")
        self.gridLayout.addWidget(self.bottomExposureEdit, 3, 1, 1, 1)
        self.zLiftDistanceEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.zLiftDistanceEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.zLiftDistanceEdit.setObjectName("zLiftDistanceEdit")
        self.gridLayout.addWidget(self.zLiftDistanceEdit, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.zLiftSpeedEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.zLiftSpeedEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.zLiftSpeedEdit.setObjectName("zLiftSpeedEdit")
        self.gridLayout.addWidget(self.zLiftSpeedEdit, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.offTimeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.offTimeEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.offTimeEdit.setObjectName("offTimeEdit")
        self.gridLayout.addWidget(self.offTimeEdit, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.layerThicknessEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.layerThicknessEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.layerThicknessEdit.setObjectName("layerThicknessEdit")
        self.gridLayout.addWidget(self.layerThicknessEdit, 1, 1, 1, 1)
        self.numberLayersEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.numberLayersEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.numberLayersEdit.setObjectName("numberLayersEdit")
        self.gridLayout.addWidget(self.numberLayersEdit, 10, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 12, 0, 1, 1)
        self.previewHEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.previewHEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.previewHEdit.setText("")
        self.previewHEdit.setObjectName("previewHEdit")
        self.gridLayout.addWidget(self.previewHEdit, 12, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setEnabled(False)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "Total Volume (ml)"))
        self.label_6.setText(_translate("MainWindow", "Bottom Layers"))
        self.label.setText(_translate("MainWindow", "X-Y Pixel size"))
        self.label_7.setText(_translate("MainWindow", "Z Lift Distance"))
        self.label_12.setText(_translate("MainWindow", "Preview Width Resolution"))
        self.label_2.setText(_translate("MainWindow", "Layer thickness"))
        self.label_5.setText(_translate("MainWindow", "Bottom Exposure(s)"))
        self.label_8.setText(_translate("MainWindow", "Z Lift Speed"))
        self.label_4.setText(_translate("MainWindow", "Off Time (s)"))
        self.label_3.setText(_translate("MainWindow", "Normal Exposure(s)"))
        self.label_9.setText(_translate("MainWindow", "Z Retract Speed"))
        self.label_11.setText(_translate("MainWindow", "Total Number of Layers"))
        self.label_13.setText(_translate("MainWindow", "Preview Height Resolution"))
        self.label_14.setText(_translate("MainWindow", "Layer 1/100"))
        self.label_15.setText(_translate("MainWindow", "Some general text information here"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

from QtImageViewer import QtImageViewer
